### ISSUE TITLE
JM's Fixes patch

### ISSUE THREAD

**Issue by DimetryBadcoder** [ShulkerSakura/SPBR#10]
Hello! 

Please, make compatibility patch for JM's Fixes! 
https://modrinth.com/resourcepack/jms-fixes

This resource pack updates some old textures to make them more consistent with the modern ones. 
Most of them are fine with SPBR, but it has connected textures and blockstates (such as turned off redstone vein), that aren't supported by SPBR

**Comment by ShulkerSakura** [comment]
Compatibility with other pack is obviously difficult and have a lot of work to do, and my computer is currently being repaired and it will take a while to retrieve it,when it come back, I need to immediately devote myself to the follow-up work on SPBR-14_2, and I can only make an Extra SPBR CTM Patch for my exist textures for the CTM textures added by JMS that what you said(glass is already existing in my main pack,bookshelf and sandstone is considered.)

**Comment by DimetryBadcoder** [comment]
Hello! 

I made a compatibility patch for Fresh Animations.
https://modrinth.com/resourcepack/spbr-x-fresh-animations

So maybe I will made another one for JM's Fixes later

**Comment by ShulkerSakura** [comment]
Nice dude，my computer is being repaired for now so If you can, you can make all of those Compatibility Patch Packs XD.

**Comment by ShulkerSakura** [comment]
BTW , what have you fixed in that pack.

**Comment by DimetryBadcoder** [comment]
> Nice dude，my computer is being repaired for now so If you can, you can make all of those Compatibility Patch Packs XD.

Okay! 
I can't guarantee, but I will try :) 

By the way, I noticed that many mobs don't have PBR. 
It would be great to make them!

**Comment by ShulkerSakura** [comment]
For vanilla pixels resolution, I really don't know how to make mobs PBR,block is much more easyer

**Comment by DimetryBadcoder** [comment]
> BTW , what have you fixed in that pack.

The Fresh Animation introduced new models with extra details, and if you use SPBR you have default textures without those details. And eye animations are missed.

I have edited textures to mix Fresh Animations ones with yours and have edited normals and speculars to suit edited textures

**Comment by ShulkerSakura** [comment]
Good job

**Comment by ShulkerSakura** [comment]
BTWx2, In fact, SPBR have three official Addon(Patch?) Pack and When my pc came back,I will upload them to Modrinth.
SPBR-GlowingOrePatch
SPBR-GrassPrallax
SPBR-BlockEmission

**Comment by DimetryBadcoder** [comment]
> BTWx2, In fact, SPBR have three official Addon(Patch?) Pack and When my pc came back,I will upload them to Modrinth. SPBR-GlowingOrePatch SPBR-GrassPrallax SPBR-BlockEmission

Good!

**Comment by DimetryBadcoder** [comment]
> > > 对于原始像素分辨率，我真的不知道如何让怪物 PBR，阻挡要容易得多
> > 
> > 
> > 嗯，基本上是一样的。 只需为实体添加“_n”和“_s”纹理即可 :) 您可以使用已经为不同方块制作的纹理来表示不同的材质。 有些怪物已经有法线和镜面反射，比如爬行者和蜘蛛
> 
> I mean,I know how to make them,but don't know how to cook them well .

I think you can just copy block parts for different mob's parts, and it will be fine

**Comment by DimetryBadcoder** [comment]
For example, piglins have golden parts, so you can use "_s" from golden block for them

**Comment by ShulkerSakura** [comment]
Gonna think about it

**Comment by DimetryBadcoder** [comment]
For the normals, you can use gradients, if the face is curved. 
For the rough materials it's good to use noisy textures, but I never tried it

**Comment by DimetryBadcoder** [comment]
If you're new for the PBR textures, I recommend to read this to understand the principles: 
https://shaderlabs.org/wiki/LabPBR_Material_Standard

**Comment by ShulkerSakura** [comment]
Bro, I make this pack for more than  5 years, I just don't know how to draw them well

**Comment by DimetryBadcoder** [comment]
Sorry, I didn't knew :D

**Comment by DimetryBadcoder** [comment]
There is an example what I've changed. 
If you load SPBR before Fresh Animations, you see open eyes under the smiling ones, and the smiling ones aren't shiny. 
And if you load Fresh Animations before SPBR, you don't have eye animations at all.

![2024-07-18_04 07 07](https://github.com/user-attachments/assets/514c7fb8-7a66-43d0-b919-b4a7b2d8ade5)

**Comment by DimetryBadcoder** [comment]
Compatibility patch fixes it
