### ISSUE TITLE
Parallax effect is not available at some coordinate for natural block

### ISSUE THREAD

**Issue by OstiumAxioma** [ShulkerSakura/SPBR#11]
As shown in this screenshot, the parallax effect for this resource pack is not available on some blocks coordinates. These blocks definitely have parallax effect, if you place it on the coordinate that has parallax effect. I am not sure if this is intentional for this pack. If it is, how can I make the parallax effect available for all coordinates?

![image](https://github.com/user-attachments/assets/dee5037b-7e31-491a-acbc-f6d20503fd95)

**Comment by ShulkerSakura** [comment]
Caused by mixed resourcepacks
