### ISSUE TITLE
在室内方块间有透光和彩色的线

### ISSUE THREAD

**Issue by Akari77777** [ShulkerSakura/SPBR#12]
![26a08eba-759b-40dd-aacd-36ce4db3fb28](https://github.com/user-attachments/assets/6ec244de-a260-43f2-afa9-0a325d4834be)
![2](https://github.com/user-attachments/assets/7a148c9f-97ad-4df7-8e1e-05421ce33c14)
![3](https://github.com/user-attachments/assets/fde9e5f0-ffcb-4468-b7d5-bf1f7b3f0087)

**Comment by ShulkerSakura** [comment]
光影对视差的支持问题

**Comment by Akari77777** [comment]
光影用的是 iterationT3.2.0 ，这个问题该咋解决
