### ISSUE TITLE
GrassParallax RP not working

### ISSUE THREAD

**Issue by Dife2K** [ShulkerSakura/SPBR#13]
Hi, i don't know if this is to be expected but after activating SPBR-GrassParallax Resource Pack, the outcome doesn't look like anything near the screenshot posted on modrinth. You can see some screenshots below and my mod/shader setup.

![2024-11-03_19 40 48](https://github.com/user-attachments/assets/fa3410d8-fcfc-4656-a8a0-9ea55f29fd42)
![image](https://github.com/user-attachments/assets/e8ad0cb1-abd8-44f6-91a2-5500e2a10c05)
![image](https://github.com/user-attachments/assets/cbd64669-e08d-4dbc-8a74-310074c7dbed)
![image](https://github.com/user-attachments/assets/e56f75d5-07d4-46a5-8eae-9e4b7b40207c)

Any help would be appreciated, Thank you!!!

**Comment by ShulkerSakura** [comment]
![2024-11-04_07 41 29](https://github.com/user-attachments/assets/6430aa68-045d-444b-a736-5344f6b35c81)
Complementary's parallax depth is lower and have no Voxel Parallax so the visual effect is little.
Set parallax depth to 1.0 can be better, and btw you should turn on the POM on cutout surface.
