### ISSUE TITLE
SPBR 16.1 has many issues on 1.21.4

### ISSUE THREAD

**Issue by Chris6ix** [ShulkerSakura/SPBR#14]
I just updated my main modpack from 1.21.1 to 1.21.4, and I noticed some issues like mobs being black sometimes, particles like slimes landing or breaking block particles to be red instead of their original color and items like swords for example turning into colored squares. After some troubleshooting, I figured out that it's SPBR's fault. Keeping everything as is and just removing SPBR fixes these issues completely. This was not an issue before when I used SPBR 15.2 on 1.21.1. My mod list and resourcepack list are attached below as screenshots and my Shader is BSL_v8.4.01.1 in case it helps.
![2024-12-14_21 10 10](https://github.com/user-attachments/assets/e6647cb6-2a63-46e3-9ce8-66c1dc2d21fd)
![2024-12-14_21 27 24](https://github.com/user-attachments/assets/f8589c29-fd7c-404a-b5d2-71aef4d2bb74)

![image](https://github.com/user-attachments/assets/602c0044-6862-4017-b340-1a2e6d7d00d8)
![image](https://github.com/user-attachments/assets/0f21a73c-d5f6-4599-95a2-91c30ab3eb47)

**Comment by ShulkerSakura** [comment]
Most issue causes by Iris for 1.21.4, parallax and PBR not working proper,and SPBR have eating animations since 16.0. I'm gonna to test the item issues.

**Comment by ShulkerSakura** [comment]
It has been tested and there is no problem except that the entity does not have PBR when only load SPBR. Recommand you upgrade to latest Iris (still have Entitys have no PBR issue)

**Comment by Chris6ix** [comment]
Ah, I didn't even know that SPBR now also has eating animations. I removed Theone's Eating Animation Pack then.
But what do you mean with "upgrade to latest Iris"? I am on the latest version. I'm using 1.8.4 for Fabric 1.21.4 as you can see in my mod list, and that is the latest version as you can see here 
![image](https://github.com/user-attachments/assets/5dafe2dc-d6a4-4ffd-8641-54d4bedb2644)

**Comment by ShulkerSakura** [comment]
Some colors changing issue (like slime have red particles) happened once in Iris 1.8.2 Test version, So I guess it might be the problem of Iris too this time.

**Comment by ShulkerSakura** [comment]
After removed eating animation pack, did you still have those bugs?

**Comment by Chris6ix** [comment]
I just tested again without the animation pack and yes all the issues are still present.
If it is actually an Iris issue as you say, can you please contact the Iris dev then and ask him to fix it?
I don't even know what the technical problem is, so I don't even know how I would report this to him.

**Comment by ShulkerSakura** [comment]
It should be fixed in Iris 1.8.5 release

**Comment by Chris6ix** [comment]
Yep, just tested. It's fixed. Thanks :)
