### ISSUE TITLE
玻璃连接纹理失效无法实现无缝玻璃

### ISSUE THREAD

**Issue by laozibashi** [ShulkerSakura/SPBR#2]
作者您好，请问在应用spbr材质包之后玻璃的无缝连接纹理失效可以处理一下吗，感谢。
顺带一提我非常喜欢您的材质包，希望能越做越好，让更多喜欢原版pbr材质的人知道。
爱来自

**Comment by ShulkerSakura** [comment]
SPBR本来就没做CTM.....emmmm

**Comment by laozibashi** [comment]
ok，感谢回复
