### ISSUE TITLE
从特定角度观察时，梯子侧面有几条线

### ISSUE THREAD

**Issue by ItIsNotAPlayer** [ShulkerSakura/SPBR#4]
这是怎么回事
![2023-01-09_17 08 14](https://user-images.githubusercontent.com/102716584/211275897-e0097b20-d518-4664-8547-43ed826cd7c7.png)
![2023-01-09_17 09 56](https://user-images.githubusercontent.com/102716584/211275988-013defcf-da26-4ebf-b545-25ef824bfb64.png)
![2023-01-09_17 11 33](https://user-images.githubusercontent.com/102716584/211276054-d3739af1-9c90-4c20-af8c-d72cce7c73f8.png)

**Comment by ShulkerSakura** [comment]
薄片视差的通病，以后会换成3D模型
