### ISSUE TITLE
Candles don't have emission

### ISSUE THREAD

**Issue by andrwcrr** [ShulkerSakura/SPBR#5]
Is it possible that you can add emission to candles? Because some shaderpacks don't have hardcoded emission and therefore candles dont emit light when using those shaderpacks.

**Comment by ShulkerSakura** [comment]
👌Your candles is on the way.

**Comment by andrwcrr** [comment]
you're awesome

**Comment by ShulkerSakura** [comment]
Can you provide a shader that matches your description?

**Comment by andrwcrr** [comment]
I've just checked and candles do have emission, the shader I was talking about was rethinking voxels, but there is something wrong with the shader I think, because the candles have emission in other packs, sorry to bother.

**Comment by ShulkerSakura** [comment]
😉
