### ISSUE TITLE
Some signs still have old textures

### ISSUE THREAD

**Issue by andrwcrr** [ShulkerSakura/SPBR#6]
![image](https://github.com/ShulkerSakura/SPBR/assets/128940455/f740637c-3926-4668-9f0e-5a089b71d2af)
Oak, spruce, birch, jungle, acacia, and dark oak signs all have the pre-1.14 textures.

**Comment by ShulkerSakura** [comment]
Copy that fix it in next release.👌

**Comment by ShulkerSakura** [comment]
[https://github.com/ShulkerSakura/SPBR/releases/tag/12.4](url)
