### ISSUE TITLE
`grass_block_side.png` is not default and still doesnt have baked lighting

### ISSUE THREAD

**Issue by andrwcrr** [ShulkerSakura/SPBR#7]
I'm not sure if this is intentional or not because you replaced almost all albedo textures with their default except for `grass_block_side.png`. If this was not your intention then this is what it looks like currently in SPBR:
![2023-12-12_01 23 45](https://github.com/ShulkerSakura/SPBR/assets/128940455/551e9752-9522-4c4b-b0e0-dd15ea689b79)
And this is what it looks like in vanilla:
![2023-12-12_01 23 36](https://github.com/ShulkerSakura/SPBR/assets/128940455/6c43006f-acbf-4781-9a01-25e707b6c9d7)
As you can see SPBR is missing some shading under the grass part of the block.

P.S. If you want the pack to have unedited vanilla textures then you can just remove all the vanilla textures from your resource pack and leave the normal and specular textures and it will use the vanilla albedos alongside your PBR textures just fine.

**Comment by ShulkerSakura** [comment]
Sorry about that I can't perfectly understand what you talking about.
If you want to say that some textures are not came from vanilla and have a little bit cripple the original texture's baked lighting,these are products from VNR，SPBR is based on VNR but no secondary processing of the vanilla texture. In next release I'm gonna fix it and add the chirseled tuff which I forgot it in the last release XD.

**Comment by andrwcrr** [comment]
For SPBR did you generally intend to re-add the baked lighting that VNR removed?

**Comment by ShulkerSakura** [comment]
Nope，I don't edit the vanilla textures just because I'm good at this.

**Comment by andrwcrr** [comment]
I think I'm overcoming the language barrier now, so from what I understand is that you did not change any of the vanilla textures from VNR when making SPBR?

**Comment by andrwcrr** [comment]
do you have a discord/ discord server where we can communicate more conveniently because i am interested in this resource pack's development

**Comment by Verix** [comment]
> Nope bro SPBR have no any official chat app group/server.

有没有粉丝qq/微信群呢？

**Comment by ShulkerSakura** [comment]
> > Nope bro SPBR have no any official chat app group/server.
> 
> 有没有粉丝qq/微信群呢？

现在有了，Q:130950489
