### ISSUE TITLE
[Suggestion] 移除/减弱雪的光源效果

### ISSUE THREAD

**Issue by Ptilopsis01** [ShulkerSakura/SPBR#9]
如题，因为光源会触发光影的bloom效果，导致进入雪原地形的时候能把人闪瞎，非常难受
![image](https://github.com/ShulkerSakura/SPBR/assets/93318731/8e3cf0e7-3650-49bd-abca-b4b3c4116c8d)

**Comment by ShulkerSakura** [comment]
应该是着色器bug，雪是没有自发光的，雪只有次表面散射

**Comment by ShulkerSakura** [comment]
请给出您的
着色器加载器
与着色器信息

**Comment by Ptilopsis01** [comment]
> 请给出您的 着色器加载器 与着色器信息

iris 1.6.17
complementary  reimagined r5.1.1

**Comment by RecRivenVI** [comment]
> > 请给出您的 着色器加载器 与着色器信息
> 
> iris 1.6.17 complementary reimagined r5.1.1

有没有对着色器默认配置做修改？除了开启LabPBR

**Comment by Ptilopsis01** [comment]
> > > 请给出您的 着色器加载器 与着色器信息
> > 
> > 
> > iris 1.6.17 complementary reimagined r5.1.1
> 
> 有没有对着色器默认配置做修改？除了开启LabPBR

有的，我发上来
[ComplementaryReimagined_r5.1.1.zip.txt](https://github.com/ShulkerSakura/SPBR/files/14747028/ComplementaryReimagined_r5.1.1.zip.txt)

**Comment by ShulkerSakura** [comment]
SPBR仅支持LabPBR标准，你开的是SEUSPBR，LabPBR是更新的标准，支持更多效果，LabPBR使用蓝色通道的50%-100%来做次表面散射，而SEUSPBR用蓝色通道保存自发光。

**Comment by Ptilopsis01** [comment]
> SPBR仅支持LabPBR标准，你开的是SEUSPBR，LabPBR是更新的标准，支持更多效果，LabPBR使用蓝色通道的50%-100%来做次表面散射，而SEUSPBR用蓝色通道保存自发光。

原来如此，现在正常了

**Comment by Ptilopsis01** [comment]
对了顺便问一下，这个材质包是只有视差没有法线么，还是说也是我设置有问题

**Comment by ShulkerSakura** [comment]
> 对了顺便问一下，这个材质包是只有视差没有法线么，还是说也是我设置有问题

SPBR是基于原版16x像素的纹理，无法制作其他原版风格但是分辨率高的那种材质包的描边法线，SPBR中的法线制作风格不一样，SPBR的法线用于体现纹理上的阴影效果

**Comment by ShulkerSakura** [comment]
> 对了顺便问一下，这个材质包是只有视差没有法线么，还是说也是我设置有问题

你掏个去皮原木出来，看看是不是圆润的，是就是法线正常

**Comment by Ptilopsis01** [comment]
> > 对了顺便问一下，这个材质包是只有视差没有法线么，还是说也是我设置有问题
> 
> 你掏个去皮原木出来，看看是不是圆润的，是就是法线正常

<img width="1281" alt="image" src="https://github.com/ShulkerSakura/SPBR/assets/93318731/b1834928-398b-4937-a717-fcc3832ad4cb">
似乎没有，我换了几个光影也是这样
